from datetime import datetime
from terraview.findings.models import Finding, Severity


def generate_report(
    findings: list[Finding],
    scan_path: str,
    provider_name: str,
    model: str,
) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    counts = _count_by_severity(findings)
    static = [f for f in findings if f.source == "static"]
    graph  = [f for f in findings if f.source == "graph"]
    llm    = [f for f in findings if f.source == "llm"]

    lines = [
        "# terraview security report",
        "",
        f"**Scan path:** `{scan_path}`  ",
        f"**Generated:** {now}  ",
        f"**Provider:** {provider_name}  ",
        f"**Model:** {model}  ",
        f"**Total findings:** {len(findings)}",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]

    for sev in Severity:
        count = counts.get(sev, 0)
        if count > 0:
            lines.append(f"| {sev.value} | {count} |")

    lines += [
        "",
        "| Source | Findings |",
        "|--------|----------|",
        f"| Static rules | {len(static)} |",
        f"| Graph traversal | {len(graph)} |",
        f"| LLM reasoning | {len(llm)} |",
        "",
    ]

    if graph:
        lines += ["## Chain findings (graph traversal)", ""]
        for f in sorted(graph, key=lambda x: _severity_order(x.severity)):
            lines += _format_finding(f)

    critical = [f for f in findings if f.severity == Severity.CRITICAL and f.source != "graph"]
    if critical:
        lines += ["## Critical findings", ""]
        for f in critical:
            lines += _format_finding(f)

    high = [f for f in findings if f.severity == Severity.HIGH]
    if high:
        lines += ["## High findings", ""]
        for f in high:
            lines += _format_finding(f)

    medium_low = [f for f in findings if f.severity in (Severity.MEDIUM, Severity.LOW)]
    if medium_low:
        lines += ["## Medium and low findings", ""]
        for f in medium_low:
            lines += _format_finding(f)

    lines += [
        "---",
        "*Generated by [terraview](https://github.com/kanchichitaliya/terraview)*",
    ]

    return "\n".join(lines)


def _format_finding(f: Finding) -> list[str]:
    lines = [
        f"### {f.id}: {f.title}",
        "",
        f"**Severity:** {f.severity.value}  ",
        f"**Resource:** `{f.resource_type}.{f.resource_name}`  ",
        f"**File:** `{f.file_path}`  ",
        f"**Source:** {f.source}  ",
    ]

    if f.mitre_technique:
        lines.append(
            f"**MITRE:** [{f.mitre_technique}](https://attack.mitre.org/techniques/"
            f"{f.mitre_technique.replace('.', '/')}): {f.mitre_tactic}  "
        )

    lines += ["", f.description, ""]

    if f.blast_radius:
        lines += ["**Blast radius:**", ""]
        for r in f.blast_radius:
            lines.append(f"- `{r}`")
        lines.append("")

    if f.remediation:
        lines += [
            "**Remediation:**",
            "",
            "```hcl",
            f.remediation,
            "```",
            "",
        ]

    return lines


def _count_by_severity(findings: list[Finding]) -> dict:
    counts = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _severity_order(s: Severity) -> int:
    return [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
            Severity.LOW, Severity.INFO].index(s)
